### ISSUE TITLE
How it should work?

### ISSUE THREAD

**Issue by bushev** [orlikoski/fanoverlord#1]
Hey,

Thank you for the great Docker image!

I'm wondering, how to use it in real life?

I mean, the ambient temp is always 25 - 26 degrees, but the CPU temp can be super hight. Looks like the script doesn't know the "real" temp.

**Comment by orlikoski** [comment]
The idrac module on these boxes are unable to measure the CPU temp and therefore the best that can be done is measuring the inside the box temp. This script allows for setting custom fan speeds based on temperatures on that sensor in each unique environment.

**Comment by bushev** [comment]
Thanks for the answer!

I feel like I can install a custom temp sensor for CPUs and pull it instead of an ambient sensor.
